### ISSUE TITLE
update version of supported Jetty 9

### ISSUE THREAD

**Issue by GoogleCodeExporter** [xzer/run-jetty-run#172]
```
Jetty 9 is in version 9.0.4.v20130625 and Run-Jetty-Run is using 9.0.0.M3.

http://search.maven.org/#artifactdetails%7Corg.eclipse.jetty%7Cjetty-runner%7C9.
0.4.v20130625%7Cjar
```

Original issue reported on code.google.com by `cvgav...@gmail.com` on 23 Jul 2013 at 7:29

**Comment by nicolas-raoul** [comment]
Please reinstall Run Jetty Run using this software update URL: http://xzer.github.io/run-jetty-run-updatesite/nightly/
This will give you access to Jetty 9.3.6 which is "only" one year old.

**Comment by cimmone** [comment]
@nicolas-raoul It looks like there is a problem with that link. Is it down or moved?

Thanks!

**Comment by nicolas-raoul** [comment]
@cimmone Indeed it seems that it is not available anymore :-/

**Comment by xzer** [comment]
@cimmone @nicolas-raoul I can install it from the update site url correctly, do you have any network issue?

**Comment by nicolas-raoul** [comment]
@xzer Sorry I have not tried in a very long time, as I now use Jetty from command-line.
