### ISSUE TITLE
RJR finding jar failed

### ISSUE THREAD

**Issue by dirichs** [xzer/run-jetty-run#189]
Running the latest run-jetty-run plugin (1.3.4) with Eclipse Mars or Luna, I get java.lang.IllegalStateException: RJR finding jar failed

This happens as soon as I choose "JNDI Support" on the run configuration page for Jetty 8.1.8.

The error message is displayed in a dialog box in Eclipse, no console output is given. If I look in the .log file in my workspace directory I can see the stack trace

`!MESSAGE Problems occurred when invoking code from plug-in: "org.eclipse.jface".`
`!STACK 0`
`java.lang.IllegalStateException: RJR finding jar failed`
`	at runjettyrun.utils.ProjectUtil.getLibs(ProjectUtil.java:150)`
`	at run_jetty_run_jetty8.Jetty8PackageProvider.getPackage(Jetty8PackageProvider.java:26)`
`	at runjettyrun.Plugin.getPackages(Plugin.java:300)`
`	at unjettyrun.utils.RunJettyRunLaunchConfigurationUtil.loadPackage(RunJettyRunLaunchConfigurationUtil.java:184)`
`	at runjettyrun.JettyLaunchConfigurationClassPathProvider.resolveClasspath(JettyLaunchConfigurationClassPathProvider.java:327)`
`	at runjettyrun.JettyLaunchConfigurationClassPathProvider.resolveClasspath(JettyLaunchConfigurationClassPathProvider.java:303)`
`	at runjettyrun.JettyLaunchConfigurationClassPathProvider.resolveRuntimeClasspathEntry(JettyLaunchConfigurationClassPathProvider.java:365)`
`	at org.eclipse.jdt.internal.launching.RuntimeClasspathEntryResolver.resolveRuntimeClasspathEntry(RuntimeClasspathEntryResolver.java:45)`
`	at org.eclipse.jdt.launching.JavaRuntime.resolveRuntimeClasspathEntry(JavaRuntime.java:942)`
`	at runjettyrun.tabs.classpath.ClasspathEntry.getChildren(ClasspathEntry.java:295)`
`	at runjettyrun.tabs.classpath.UserClassesClasspathContentProvider.getChildren(UserClassesClasspathContentProvider.java:155)`
`	at org.eclipse.jface.viewers.AbstractTreeViewer.getRawChildren(AbstractTreeViewer.java:1372)`
`	[...]`

**Comment by xzer** [comment]
could you please try the nightly build of 1.3.5 from http://xzer.github.io/run-jetty-run/, I did not reproduce this issue at 1.3.5.

**Comment by dirichs** [comment]
The problem has disappeared with the nightly build, thanks a lot!

**Comment by dart2Ashu** [comment]
Hi, I  tried installing the plugin thro' marketplace as well as the nightly build of 1.3.5 from http://xzer.github.io/run-jetty-run/, but it doesn't work. I am gettting the error-No repositories found at http://xzer.github.io/run-jetty-run-updatesite/current.
