### ISSUE TITLE
Old embeded Jetty 9 does not support Java 8 lambda

### ISSUE THREAD

**Issue by michaldo** [xzer/run-jetty-run#191]
My code use Java 8 lambda and Jetty fails. I found a solution here: http://stackoverflow.com/a/33481641/2365727
But I don't know how to update Jetty version.

Please update embeded Jetty or add instruction how to use external jetty installation (if possible).

**Comment by xzer** [comment]
uninstall the old plugin and reinstall the newest 1.3.5 nightly build at http://xzer.github.io/run-jetty-run/, then specify the jetty version to 9.3 from your launcher configuration.

**Comment by michaldo** [comment]
Thanks, it helped me.
(I didn't close this ticket because 1.3.5 is not released yet)

**Comment by xzer** [comment]
I have modified the description in readme, close this ticket.
