### ISSUE TITLE
Eclipse update site no longer active

### ISSUE THREAD

**Issue by irobertson** [xzer/run-jetty-run#192]
In https://github.com/xzer/run-jetty-run/wiki/GettingStarted, we are instructed to point eclipse at http://run-jetty-run.googlecode.com/svn/trunk/updatesite. Unfortunately, that URL serves up a 404  (presumably related to http://run-jetty-run.googlecode.com/ redirecting to github).

If there is already a new update site, can the docs be updated to reflect that? If not, can one be created? Failing that, what would be involved in building one locally that I could point my eclipse at?

**Comment by xzer** [comment]
At first, you can find the current update site address at the top page of this project under the "INSTALL" section.

However thanks very much for your report, we missed out the wiki when we migrated this project from google code to github.

The wiki has been fixed. Thanks again.
