### ISSUE TITLE
No repository found at http://xzer.github.io/run-jetty-run-updatesite/current/.

### ISSUE THREAD

**Issue by dart2Ashu** [xzer/run-jetty-run#194]
Hi, I tried installing the plugin thro' marketplace as well as the nightly build of 1.3.5 from http://xzer.github.io/run-jetty-run/, but it doesn't work. I am gettting the error-No repositories found at http://xzer.github.io/run-jetty-run-updatesite/current.

**Comment by xzer** [comment]
"http://xzer.github.io/run-jetty-run-updatesite/current/" works fine for me. 

You can try "http://xzer.github.io/run-jetty-run-updatesite/nightly/" which is currently recommended version.

If it does not work yet, I guess you can try to check your local firewall configuration or local network gateway configuration.

**Comment by xzer** [comment]
no response, close.
