### ISSUE TITLE
Update site broken

### ISSUE THREAD

**Issue by basinilya** [xzer/run-jetty-run#200]
I can't install the plugin in Eclipse 4.4 via Help/Install new software,
    
    Unable to read repository at http://xzer.github.io/run-jetty-run-updatesite/nightly/content.xml.
    Unable to read repository at http://xzer.github.io/run-jetty-run-updatesite/nightly/content.xml.
    xzer.github.io failed to respond

**Comment by xzer** [comment]
I am sorry to reply too late due to some private issue.

I tested installing and there was no error reported. I believe it was a temporary network failure. 

Close this issue.
