### ISSUE TITLE
How to add support for Jetty 9.4.6.v20170531

### ISSUE THREAD

**Issue by ffoysal** [xzer/run-jetty-run#205]
Hello Contributors,
Is there any contributing guideline for this repo. We need the latest version of Jetty (9.4.6.v20170531) to be included in the plugin 

Thanks

**Comment by xzer** [comment]
there is no guide line for that,  but you can simply copy the implementation for 9.3.

there are some duplicated source, especially the bootstrap classes are copied into every plugin for each version of jetty. I planned to address this, but not yet.

so, just copy it😓

**Comment by ffoysal** [comment]
Created PR #206
