### ISSUE TITLE
Cannot update from nightly update site

### ISSUE THREAD

**Issue by ffoysal** [xzer/run-jetty-run#207]
I was trying install latest plugin from http://xzer.github.io/run-jetty-run-updatesite/nightly/ and got an error.
I am using eclipse luna, JDK 7. Please see the screen shot. 
![new_plugin_install_error](https://user-images.githubusercontent.com/6124333/28833817-81fabad8-76ae-11e7-9aff-3e979c11021e.png)

Help is very much appreciated or a hint to fix it.

**Comment by ffoysal** [comment]
was able to install in eclipse orxigen. don't know whats wrong with eclipse luna

**Comment by xzer** [comment]
The jetty version over 9.0 requires jdk 8, which may be the reason.

**Comment by ffoysal** [comment]
I can successfully do it from eclipse market place though, Is there any plan soon to put the latest release in eclipse market place, we need it badly :(

**Comment by xzer** [comment]
I have updated eclipse market, sorry for let you wait.

**Comment by ffoysal** [comment]
![selection_001](https://user-images.githubusercontent.com/6124333/28929347-b900ad9a-783d-11e7-9645-562291a6d905.png)
Thought the latest version would be 1.3.5

**Comment by xzer** [comment]
please try again

**Comment by ffoysal** [comment]
Thanks, I got it installed but when try to configure only 'Jetty 9.0.0.M3' is available, Other versions are not shown in the dropdown. any idea ?
![install_details](https://user-images.githubusercontent.com/6124333/28930687-bd802c48-7841-11e7-8cbe-df1b88881340.png)
![selection_002](https://user-images.githubusercontent.com/6124333/28930695-c708c52c-7841-11e7-94a3-ac1ae11e556f.png)
I am running jdk1.8

**Comment by xzer** [comment]
I am sorry that I was busy from last week. It seems that you did not test the plugin before submit your PR...

well, it is necessary to add the pulldown option to the UI feature. You can push a PR again, or just wait for me.

**Comment by ffoysal** [comment]
Thanks @xzer . Something was wrong in my eclipse. Now working perfectly.
![selection_004](https://user-images.githubusercontent.com/6124333/29103845-111e5576-7c90-11e7-9163-cff3ee0c94d0.png)

Looks everything working fine. Closing the issue. sorry for noise.
