### ISSUE TITLE
Update site is down

### ISSUE THREAD

**Issue by johanwasserman** [xzer/run-jetty-run#210]
404 on http://xzer.github.io/run-jetty-run-updatesite/nightly/

Bad news for my project deadline

**Comment by xzer** [comment]
it is a eclipse update site link, you should use it via eclipse's install new software menu rather than access it via browser.

**Comment by chang-chao** [comment]
index.html is added to update site to avoid the frightening 404 error

**Comment by johanwasserman** [comment]
![image](https://user-images.githubusercontent.com/7691625/36293773-e3c78ea8-132f-11e8-87d9-ede116f4b5c9.png)

Does that help?

**Comment by johanwasserman** [comment]
Never mind, we all installed Eclipse Jetty.

**Comment by chang-chao** [comment]
@johanwasserman The artifact file was there  and you can check whether it can be downloaded using a browser.If not,check you network firewall or proxy settings.

http://xzer.github.io/run-jetty-run-updatesite/nightly/plugins/runjettyrun_1.3.5.201802101211.jar

Anyway,glad that you solved the problem by installing Eclipse Jetty.
